#!/usr/bin/env bash
_echo()
{
  if [ "X$1" = "X-n" ]; then
    shift
    printf "%s" "$*"
  else
    printf "%s\n" "$*"
  fi
}

spark()
{
  declare -i n
  declare -a numbers
  declare -i min=$(printf '%u' -1) max=0

  for n in ${@//,/ }
  do
    n=${n%.*}
    (( n < min )) && min=$n
    (( n > max )) && max=$n
    numbers+=($n)
  done

  local ticks=(▁ ▂ ▃ ▄ ▅ ▆ ▇ █)
  (( min == max )) && ticks=(▅ ▆)

  declare -i f=$(( (($max-$min)<<8)/(${#ticks[@]}-1) ))
  (( f < 1 )) && f=1

  for n in "${numbers[@]}"
  do
    _echo -n "${ticks[$(( ((($n-$min)<<8)/$f) ))]}"
  done
  _echo
}

if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
  help()
  {
    local spark=$(basename "$0")
    cat <<EOF

    USAGE:
      $spark [-h|--help] VALUE,...

    EXAMPLES:
      $spark 1 5 22 13 53
      ▁▁▃▂█
      $spark 0,30,55,80,33,150
      ▁▂▃▄▂█
      echo 9 13 5 17 1 | $spark
      ▄▆▂█▁
EOF
  }

  if { [[ -z "$1" ]] && [[ -t 0 ]] ; } || [[ "$1" == '-h' ]] || [[ "$1" == '--help' ]]
  then
    help
    exit 0
  fi

  spark "${@:-$(cat)}"
fi
